# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HazardDetector
                                 A QGIS plugin
 Hazard detection using Prithvi EO 2.0 Foundation Model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-03
        copyright            : (C) 2026 by Julia Anna Leonardi
        email                : juliaanna.leonardi@polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HazardDetector class from file HazardDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hazard_detector import HazardDetector
    return HazardDetector(iface)
