# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HazardDetectorDialog
                                 A QGIS plugin
 Hazard detection using Prithvi EO 2.0 Foundation Model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-03
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Julia Anna Leonardi
        email                : juliaanna.leonardi@polimi.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import requests

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), 'hazard_detector_dialog.ui')
    )

class HazardDetectorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(HazardDetectorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.setWindowTitle("Prithvi Hazard Detection")
        self.layer_input.layerChanged.connect(self.on_layer_changed)
        self.on_layer_changed()
        self.sensor_type.addItems(["S2_L1C", "S2_L2A", "L8_L2", "HLS"])
        
        self.buttonBox.accepted.disconnect() 
        self.buttonBox.accepted.connect(self.handle_ok)
    
    def handle_ok(self):
        if self.validate_inputs():
            self.accept()
    
    def validate_inputs(self):
        server_url = self.txt_url.text().strip()
        if not server_url:
            QMessageBox.warning(self, "Input Error", "The Backend Server address cannot be empty.")
            return False
        
        try:
            response = requests.get(server_url, timeout=2)
            if response.status_code != 200:
                QMessageBox.critical(self, "Connection Error", f"Server reached but returned error: {response.status_code}")
                return False
        except Exception as e:
            QMessageBox.critical(self, "Connection Error", f"Could not connect to backend: {str(e)}")
            return False

        return True

    def on_layer_changed(self):
        layer = self.layer_input.currentLayer()
        if not layer:
            return 
        
        count = layer.bandCount()
        self.combo_blue.setLayer(layer)
        self.combo_green.setLayer(layer)
        self.combo_red.setLayer(layer)
        self.combo_nir.setLayer(layer)
        self.combo_swir1.setLayer(layer)
        self.combo_swir2.setLayer(layer)
        
        if count == 6:
            self.combo_blue.setBand(1)
            self.combo_green.setBand(2)
            self.combo_red.setBand(3)
            self.combo_nir.setBand(4)
            self.combo_swir1.setBand(5)
            self.combo_swir2.setBand(6)
            

    def get_inputs(self):
        """Returns a dictionary of all user selections from the UI."""
        return {
            "layer": self.layer_input.currentLayer(),
            "sensor": self.sensor_type.currentText(),
            "bands": [
                self.combo_blue.currentBand(),
                self.combo_green.currentBand(),
                self.combo_red.currentBand(),
                self.combo_nir.currentBand(),
                self.combo_swir1.currentBand(),
                self.combo_swir2.currentBand()
            ]
        }